Repository qonto/ember-lottie, pull requests merged in 2023-10, with the labels that each got.

#206 feat(dev-deps): upgrade ember-source from ~4.11.0 to ~5.3.0
  .github/workflows/ci.yml
  ember-lottie/package.json
  pnpm-lock.yaml
  test-app/config/ember-try.js
  test-app/package.json
Labels: dependencies

#208 feat(dev-deps): Bump @embroider/test-setup from 2.1.1 to 3.0.2 in /test-app
  pnpm-lock.yaml
  test-app/package.json
Labels: dependencies

#211 chore(deps-dev): bump @typescript-eslint/parser in /ember-lottie
  ember-lottie/package.json
  pnpm-lock.yaml
Labels: dependencies

#213 Bump @glint/environment-ember-loose from 0.9.7 to 1.2.1 in /ember-lottie
  ember-lottie/package.json
  pnpm-lock.yaml
Labels: dependencies

#214 chore(deps-dev): bump @glint/core from 0.9.7 to 1.2.1 in /ember-lottie
  ember-lottie/package.json
  pnpm-lock.yaml
Labels: dependencies

#215 chore(deps-dev): bump eslint-plugin-ember from 10.6.1 to 11.11.1 in /ember-lottie
  ember-lottie/package.json
  pnpm-lock.yaml
Labels: dependencies

#216 chore(deps-dev): bump @babel/core from 7.21.3 to 7.23.0 in /ember-lottie
  ember-lottie/package.json
  pnpm-lock.yaml
Labels: dependencies

#218 chore(deps-dev): bump concurrently from 7.6.0 to 8.2.1 in /ember-lottie
  ember-lottie/package.json
  pnpm-lock.yaml
Labels: dependencies

#219 chore(deps-dev): bump @babel/plugin-proposal-decorators from 7.21.0 to 7.23.0 in /ember-lottie
  ember-lottie/package.json
  pnpm-lock.yaml
Labels: dependencies

#221 chore(deps-dev): bump @typescript-eslint/eslint-plugin from 5.59.6 to 6.7.4 in /ember-lottie
  ember-lottie/package.json
  pnpm-lock.yaml
Labels: dependencies

#234 feat(dev-deps): remove ember-data from project
  pnpm-lock.yaml
  test-app/package.json
  test-app/types/ember-data/types/registries/model.d.ts
Labels: dependencies

#235 chore(deps-dev): bump ember-cli from 4.11.0 to 4.12.2 in /test-app
  pnpm-lock.yaml
  test-app/package.json
Labels: dependencies

#236 feat(dev-deps): remove @embroider/compat, @embroider/core, and @embroider/webpack
  pnpm-lock.yaml
  test-app/package.json
Labels: dependencies

#237 feat: use official ember-source TypeScript types public preview
  pnpm-lock.yaml
  test-app/config/ember-try.js
  test-app/package.json
  test-app/types/test-app/index.d.ts
Labels: enhancement

#238 feat: use official ember-source TypeScript types public preview in addon package
  ember-lottie/package.json
  ember-lottie/src/unpublished-development-types/index.d.ts
  ember-lottie/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement

#239 chore(dev-deps): bump eslint and prettier related dependencies to latest
  ember-lottie/package.json
  ember-lottie/src/components/lottie.ts
  ember-lottie/src/unpublished-development-types/index.d.ts
  package.json
  pnpm-lock.yaml
  test-app/package.json
  test-app/tests/integration/components/lottie-test.ts
Labels: dependencies

#240 chore(lint): add specific set of rules for TypeScript linting and run lint with --fix option
  ember-lottie/.eslintrc.js
  ember-lottie/src/components/lottie.ts
  ember-lottie/src/template-registry.ts
  ember-lottie/src/unpublished-development-types/index.d.ts
  test-app/.eslintrc.js
  test-app/app/config/environment.d.ts
  test-app/tests/helpers/index.ts
  test-app/tests/integration/components/lottie-test.ts
  test-app/types/global.d.ts
Labels: internal

#241 feat(ts): setup and use Glint in test-app package
  pnpm-lock.yaml
  test-app/package.json
  test-app/tests/integration/components/lottie-test.ts
  test-app/tsconfig.json
  test-app/types/glint.d.ts
Labels: internal

#252 fix(docs): remove unused columns in API reference table
  README.md
Labels: documentation

#253 ci: add TypeScript compatibility check jobs
  .github/workflows/ci.yml
  README.md
  package.json
Labels: internal

#260 chore: install and use @qonto/eslint-config-typescript@1.0.0-rc.0
  ember-lottie/.eslintrc.js
  ember-lottie/package.json
  pnpm-lock.yaml
  test-app/.eslintrc.js
  test-app/package.json
Labels: internal
