Repository qonto/ember-lottie, pull requests merged in 2023-11, with the labels that each got.

#273 Add backward compatibility with MediaQueryList.addEventListener in older browsers
  ember-lottie/src/components/lottie.ts
  test-app/tests/integration/components/lottie-test.ts
Labels: bug

#274 fix(lottie.ts): passing credentials include param to fetch request
  README.md
  ember-lottie/src/components/lottie.ts
  test-app/tests/integration/components/lottie-test.ts
Labels: enhancement

#285 feat: drop node v16
  .github/workflows/ci.yml
  README.md
  package.json
  test-app/package.json
Labels: breaking

#308 chore(deps-dev): bump typescript from 5.2.2 to 5.3.2
  .github/workflows/ci.yml
  ember-lottie/package.json
  pnpm-lock.yaml
  test-app/package.json
Labels: dependencies
