Repository qonto/ember-lottie, pull requests merged in 2023-09, with the labels that each got.

#194 Expose template registry and drop rollup-plugin-ts
  .gitignore
  README.md
  ember-lottie/.eslintignore
  ember-lottie/package.json
  ember-lottie/rollup.config.mjs
  ember-lottie/src/components/lottie.ts
  ember-lottie/src/template-registry.ts
  ember-lottie/src/unpublished-development-types/index.d.ts
  ember-lottie/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement

#203 Use correct syntax for no-lockfile option
  .github/workflows/ci.yml
Labels: internal

#204 fix: typo in README
  README.md
Labels: documentation
